add readme template
Kenji-H/beam-examples pull request #5
Opened 2018-07-03 14:15 UTC by Kenji-H

### Summary
- adde readme template
- update readme

### Issues
- resolve #3

2018-07-04 14:47 UTC, byam commented on README.md
> +
Could you add `gcs-triggered` here?

2018-07-04 15:03 UTC, byam requested changes
It would be better if examples are provided. For example you can write here `Word Count` scenario.

2018-07-04 15:03 UTC, byam commented on README-template.md
> +Create a Pub/Sub topic.
Create a topic, if you have not?

2018-07-24 12:54 UTC, Kenji-H commented
@byam Thanks for your review. I updated the files.

2018-07-25 07:14 UTC, byam approved these changes
LGTM!

2018-07-25 16:10 UTC, merged